### ISSUE TITLE
[BUG] cargo make test fails out of the box

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-rs#45]
**What is the bug?**
Following https://github.com/opensearch-project/opensearch-rs/blob/main/DEVELOPER_GUIDE.md, run `cargo make test`. The certs tests are failing (container failed to start?).

```
~/source/opensearch-project/opensearch-rs/dblock-opensearch-rs (test-matrix)$ cargo make test
[cargo-make] INFO - cargo make 0.35.11
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: test
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "./.ci/run-opensearch.sh"
INFO: Running opensearch latest
INFO: Creating network search-rest-test if it does not exist already
7061dca675c92cccd6c40bc70b0f4b682766a51182f6ebbf52fb4291240c8647
INFO: Take down node if called twice with the same arguments (DETACH=true) or on seperate terminals
INFO: Removing volume instance-rest-test-data
INFO: Removing volume instance-rest-test-data
instance-rest-test-data
0: 9200 https://localhost:9200
INFO: building opensearch container
cluster is opensearch
Sending build context to Docker daemon  2.719MB
Step 1/6 : ARG STACK_VERSION
Step 2/6 : FROM "opensearchproject/opensearch:$STACK_VERSION"
 ---> 1f7403158bcf
Step 3/6 : ARG SECURE_INTEGRATION
 ---> Using cache
 ---> 97b17916d521
Step 4/6 : ARG opensearch_path=/usr/share/opensearch
 ---> Using cache
 ---> f009b16cbc97
Step 5/6 : ARG opensearch_yml=$opensearch_path/config/opensearch.yml
 ---> Using cache
 ---> 053b2daeb2ea
Step 6/6 : RUN if [ "$SECURE_INTEGRATION" != "true" ] ; then $opensearch_path/bin/opensearch-plugin remove opensearch-security; fi
 ---> Using cache
 ---> ee5c8c68c3b9
Successfully built ee5c8c68c3b9
Successfully tagged opensearch-secure-true:latest
INFO: Starting container instance
+ [[ true == \t\r\u\e ]]
+ healthcmd='curl -vvv -s --insecure -u admin:admin --fail https://localhost:9200/_cluster/health || exit 1'
++ echo curl -vvv -s --insecure -u admin:admin --fail https://localhost:9200/_cluster/health '||' exit 1
+ docker run --name instance --network search-rest-test --env 'ES_JAVA_OPTS=-Xms1g -Xmx1g' --env node.name=instance --env cluster.name=search-rest-test --env cluster.initial_master_nodes=instance --env discovery.seed_hosts=insta
nce --env cluster.routing.allocation.disk.threshold_enabled=false --env bootstrap.memory_lock=true --env node.attr.testattr=test --env path.repo=/tmp --env 'repositories.url.allowed_urls=http://snapshot.test*' --env action.destr
uctive_requires_name=false --env node.name=instance --volume instance-rest-test-data:/usr/share/opensearch/data0 --publish 9200:9200 --ulimit nofile=65536:65536 --ulimit memlock=-1:-1 --detach=true '--health-cmd=curl -vvv -s --i
nsecure -u admin:admin --fail https://localhost:9200/_cluster/health || exit 1' --health-interval=2s --health-retries=20 --health-timeout=2s --rm -d opensearch-secure-true
66342aac22ecedbe3df93b51e3b8cec3e8028dc20e2ea1494984f9ced2dc2612
+ set +x


INFO: waiting for node instance to be up
INFO: Removing network search-rest-test
search-rest-test
SUCCESS: Cleaned up and exiting

ERROR: Failed to start instance in detached mode beyond health checks
ERROR: dumped the docker log before shutting the node down

SUCCESS run-tests
[cargo-make] INFO - Execute Command: "cargo" "test" "-p" "opensearch"
    Finished test [unoptimized + debuginfo] target(s) in 0.10s
     Running unittests src/lib.rs (target/debug/deps/opensearch-9c704994a214f91a)

running 24 tests
test http::request::tests::bytes_body_returns_usable_buf ... ok
test http::request::tests::bytes_body_writes_to_bytes_mut ... ok
test http::request::tests::bytes_slice_body_writes_to_bytes_mut ... ok
test http::request::tests::bodies_into_ndbody_writes_to_bytes ... ok
test http::request::tests::string_body_writes_to_bytes_mut ... ok
test http::request::tests::serialize_into_jsonbody_writes_to_bytes ... ok
test http::request::tests::string_slice_body_writes_to_bytes_mut ... ok
test http::request::tests::vec_body_writes_to_bytes_mut ... ok
test http::response::tests::deserialize_error_string ... ok
test http::response::tests::deserialize_index_not_found_exception ... ok
test http::transport::tests::connection_url_with_no_path_and_trailing_slash ... ok
test http::transport::tests::connection_url_with_no_path_and_no_trailing_slash ... ok
test params::tests::serialize_slices_auto ... ok
test http::transport::tests::connection_url_with_trailing_slash ... ok
test http::transport::tests::connection_url_with_no_trailing_slash ... ok
test http::response::tests::deserialize_illegal_argument_exception ... ok
test params::tests::serialize_slices_count ... ok
test tests::build_search_on_all_indices_and_types ... ok
test tests::build_search_on_selected_indices ... ok
test tests::build_search_on_selected_indices_and_types ... ok
test root::bulk::tests::serialize_bulk_operations_with_different_types_writes_to_bytes ... ok
test tests::percent_encode_characters ... ok
test root::bulk::tests::serialize_bulk_operations_with_same_type_writes_to_bytes ... ok
test http::transport::tests::invalid_pkcs12_cert_credentials ... ok

test result: ok. 24 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/auth.rs (target/debug/deps/auth-9256b3c24e58b89c)

running 3 tests
test basic_auth_header ... ok
test bearer_header ... ok
test api_key_header ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.30s

     Running tests/cert.rs (target/debug/deps/cert-333d1668bb1e5deb)

running 8 tests
test certificate_certificate_ca_validation ... FAILED
test full_certificate_ca_validation ... FAILED
test none_certificate_validation ... FAILED
test full_certificate_ca_chain_validation ... FAILED
test default_certificate_validation ... FAILED
test fail_certificate_certificate_validation ... FAILED
test certificate_certificate_validation ... FAILED
test full_certificate_validation ... FAILED

failures:
---- certificate_certificate_ca_validation stdout ----
Error: Error { kind: Http(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(9200), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }) }
thread 'certificate_certificate_ca_validation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/082e4ca49770ebc9cb0ee616f3726a67471be8cb/library/test/src/lib.rs:185:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- full_certificate_ca_validation stdout ----
Error: Error { kind: Http(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(9200), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }) }
thread 'full_certificate_ca_validation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/082e4ca49770ebc9cb0ee616f3726a67471be8cb/library/test/src/lib.rs:185:5

---- none_certificate_validation stdout ----
Error: Error { kind: Http(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(9200), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }) }
thread 'none_certificate_validation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/082e4ca49770ebc9cb0ee616f3726a67471be8cb/library/test/src/lib.rs:185:5

---- full_certificate_ca_chain_validation stdout ----
Error: Error { kind: Http(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(9200), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }) }
thread 'full_certificate_ca_chain_validation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/082e4ca49770ebc9cb0ee616f3726a67471be8cb/library/test/src/lib.rs:185:5

---- default_certificate_validation stdout ----
thread 'default_certificate_validation' panicked at 'Expected error message to contain 'unable to get local issuer certificate' but was 'error sending request for url (http://localhost:9200/): error trying to connect: tcp connect error: Connection refused (os error 111)'', opensearch/tests/cert.rs:67:13

---- fail_certificate_certificate_validation stdout ----
thread 'fail_certificate_certificate_validation' panicked at 'Expected error message to contain 'unable to get local issuer certificate' but was 'error sending request for url (http://localhost:9200/): error trying to connect: tcp connect error: Connection refused (os error 111)'', opensearch/tests/cert.rs:285:13

---- certificate_certificate_validation stdout ----
thread 'certificate_certificate_validation' panicked at 'Expected error message to contain 'unable to get local issuer certificate' but was 'error sending request for url (http://localhost:9200/): error trying to connect: tcp connect error: Connection refused (os error 111)'', opensearch/tests/cert.rs:241:17

---- full_certificate_validation stdout ----
thread 'full_certificate_validation' panicked at 'Expected error message to contain 'unable to get local issuer certificate' but was 'error sending request for url (http://localhost:9200/): error trying to connect: tcp connect error: Connection refused (os error 111)'', opensearch/tests/cert.rs:193:17


failures:
    certificate_certificate_ca_validation
    certificate_certificate_validation
    default_certificate_validation
    fail_certificate_certificate_validation
    full_certificate_ca_chain_validation
    full_certificate_ca_validation
    full_certificate_validation
    none_certificate_validation

test result: FAILED. 0 passed; 8 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.68s

error: test failed, to rerun pass '-p opensearch --test cert'
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.
```

**What is the expected behavior?**
Tests to pass.

**Comment by dblock** [comment]
My first problem was that the docker container won't start. To debug:

```
docker run --name test_1 -d opensearch-secure-true
docker logs test_1
```

There was an error in there saying my `vm.max_map_count` was too low.

Ran these from https://github.com/opensearch-project/opensearch-rs/blob/main/.github/workflows/test-integrations.yml#L24.

```
sudo swapoff -a
sudo sysctl -w vm.swappiness=1
sudo sysctl -w fs.file-max=262144
sudo sysctl -w vm.max_map_count=262144
```

Tests now try to get the wrong URL, setting `OPENSEARCH_URL` helps resolve some failures.

```
OPENSEARCH_URL=https://localhost:9200 cargo make test

running 8 tests
test full_certificate_ca_chain_validation ... FAILED
test certificate_certificate_ca_validation ... FAILED
test full_certificate_ca_validation ... FAILED
test none_certificate_validation ... ok
test fail_certificate_certificate_validation ... ok
test default_certificate_validation ... ok
test certificate_certificate_validation ... ok
test full_certificate_validation ... ok

---- full_certificate_ca_chain_validation stdout ----
Error: Error { kind: Http(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(9200), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "../ssl/statem/statem_clnt.c", line: 1913 }]))) }, X509VerifyResult { code: 20, error: "unable to get local issuer certificate" })) }) }
thread 'full_certificate_ca_chain_validation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/082e4ca49770ebc9cb0ee616f3726a67471be8cb/library/test/src/lib.rs:185:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by dz-s** [comment]
```
running 8 tests
test certificate_certificate_ca_validation ... ok
test full_certificate_ca_chain_validation ... ok
test full_certificate_ca_validation ... ok
test default_certificate_validation ... ok
test fail_certificate_certificate_validation ... ok
test none_certificate_validation ... ok
test certificate_certificate_validation ... FAILED
test full_certificate_validation ... FAILED
```

Interesting, I was able some of yours, but failed others.

**Comment by dblock** [comment]
@dz-s I think this is something about cert setup out of the box, needs debugging

**Comment by dblock** [comment]
This is because by default tests try to connect to a live endpoint.
